"""
PDF Export Module - Creates professional campaign brief PDFs using ReportLab
"""
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from io import BytesIO
import requests
from PIL import Image as PILImage


def create_campaign_pdf(campaign: dict, trend: str, category: str, image_url: str = None) -> BytesIO:
    """
    Creates a professional PDF campaign brief using ReportLab.
    
    Args:
        campaign: Dictionary with hero_concept, slogan, social_post, moodboard
        trend: The cultural trend name
        category: Trend category (sports, entertainment, etc.)
        image_url: URL of generated image
    
    Returns:
        BytesIO object containing the PDF
    """
    
    # Create PDF buffer
    pdf_buffer = BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=A4,
                          rightMargin=72, leftMargin=72,
                          topMargin=72, bottomMargin=18)
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=36,
        textColor=colors.HexColor('#F40009'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading2'],
        fontSize=24,
        textColor=colors.HexColor('#F40009'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    trend_style = ParagraphStyle(
        'TrendStyle',
        parent=styles['Heading1'],
        fontSize=32,
        textColor=colors.white,
        spaceAfter=40,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    section_style = ParagraphStyle(
        'SectionStyle',
        parent=styles['Heading2'],
        fontSize=20,
        textColor=colors.HexColor('#F40009'),
        spaceAfter=12,
        spaceBefore=20,
        fontName='Helvetica-Bold',
        borderWidth=0,
        borderPadding=0,
        leftIndent=0,
        borderColor=colors.HexColor('#F40009')
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12
    )
    
    slogan_style = ParagraphStyle(
        'SloganStyle',
        parent=styles['BodyText'],
        fontSize=24,
        textColor=colors.white,
        alignment=TA_CENTER,
        fontStyle='italic',
        spaceAfter=20,
        spaceBefore=20,
        backColor=colors.HexColor('#F40009'),
        borderPadding=20
    )
    
    # COVER PAGE
    # Create a table for the cover page with red background
    cover_data = [
        [Paragraph('COCA-COLA', title_style)],
        [Paragraph('Real Magic Campaign', subtitle_style)],
        [Spacer(1, 0.5*inch)],
        [Paragraph(trend.upper(), trend_style)],
    ]
    
    # Add image if available
    if image_url:
        try:
            img_response = requests.get(image_url, timeout=10)
            if img_response.status_code == 200:
                img_buffer = BytesIO(img_response.content)
                pil_img = PILImage.open(img_buffer)
                # Resize if too large
                max_width, max_height = 400, 300
                if pil_img.width > max_width or pil_img.height > max_height:
                    pil_img.thumbnail((max_width, max_height), PILImage.Resampling.LANCZOS)
                    img_buffer = BytesIO()
                    pil_img.save(img_buffer, format='PNG')
                    img_buffer.seek(0)
                
                cover_data.append([Spacer(1, 0.3*inch)])
                cover_data.append([Image(img_buffer, width=400, height=300)])
        except:
            pass
    
    cover_data.append([Spacer(1, 0.5*inch)])
    cover_data.append([Paragraph(f'Generated by CokeSense • {datetime.now().strftime("%B %d, %Y")}', 
                                ParagraphStyle('Footer', parent=styles['Normal'], fontSize=10, 
                                              textColor=colors.white, alignment=TA_CENTER))])
    
    cover_table = Table(cover_data, colWidths=[6*inch])
    cover_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F40009')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    
    elements.append(cover_table)
    elements.append(PageBreak())
    
    # EXECUTIVE SUMMARY PAGE
    elements.append(Paragraph('Executive Summary', section_style))
    elements.append(Spacer(1, 0.2*inch))
    
    summary_text = f"""
    <b>Campaign Overview:</b><br/><br/>
    This campaign leverages the cultural moment of <b>{trend}</b> to create authentic, 
    engaging content that resonates with Coca-Cola's "Real Magic" brand platform. The campaign 
    is designed to connect with audiences through shared cultural experiences and moments of joy.
    """
    elements.append(Paragraph(summary_text, body_style))
    elements.append(Spacer(1, 0.3*inch))
    
    # Metrics table
    metrics_data = [
        ['Category', 'Generated'],
        [category.title(), datetime.now().strftime("%B %d, %Y")]
    ]
    metrics_table = Table(metrics_data, colWidths=[3*inch, 3*inch])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F40009')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#F40009'))
    ]))
    elements.append(metrics_table)
    elements.append(PageBreak())
    
    # CAMPAIGN CONCEPT PAGE
    elements.append(Paragraph('Campaign Concept', section_style))
    elements.append(Spacer(1, 0.2*inch))
    
    elements.append(Paragraph('Hero Concept', 
                            ParagraphStyle('SubSection', parent=section_style, fontSize=16)))
    hero_text = campaign.get('hero_concept', 'N/A').replace('\n', '<br/>')
    elements.append(Paragraph(hero_text, body_style))
    elements.append(Spacer(1, 0.3*inch))
    
    elements.append(Paragraph('Slogan', 
                            ParagraphStyle('SubSection', parent=section_style, fontSize=16)))
    slogan_text = f'"{campaign.get("slogan", "N/A")}"'
    elements.append(Paragraph(slogan_text, slogan_style))
    elements.append(PageBreak())
    
    # CONTENT ASSETS PAGE
    elements.append(Paragraph('Content Assets', section_style))
    elements.append(Spacer(1, 0.2*inch))
    
    elements.append(Paragraph('Social Post', 
                            ParagraphStyle('SubSection', parent=section_style, fontSize=16)))
    social_text = campaign.get('social_post', 'N/A').replace('\n', '<br/>')
    elements.append(Paragraph(social_text, body_style))
    elements.append(Spacer(1, 0.3*inch))
    
    elements.append(Paragraph('Moodboard', 
                            ParagraphStyle('SubSection', parent=section_style, fontSize=16)))
    moodboard_text = f"<b>Creative Direction:</b><br/>{campaign.get('moodboard', 'N/A')}"
    elements.append(Paragraph(moodboard_text, body_style))
    elements.append(PageBreak())
    
    # RECOMMENDATIONS PAGE
    elements.append(Paragraph('Recommendations & Next Steps', section_style))
    elements.append(Spacer(1, 0.2*inch))
    
    recommendations_text = f"""
    <b>Posting Strategy:</b><br/>
    • Post during peak engagement hours (6-8 PM EST)<br/>
    • Use relevant hashtags related to {trend}<br/>
    • Engage with user comments to build community<br/>
    • Consider cross-platform posting (Instagram, Twitter, LinkedIn)<br/><br/>
    
    <b>Content Variations:</b><br/>
    • Instagram Stories format<br/>
    • Twitter/X thread format<br/>
    • LinkedIn professional format<br/>
    • Video content (if applicable)
    """
    elements.append(Paragraph(recommendations_text, body_style))
    
    # Build PDF
    doc.build(elements)
    pdf_buffer.seek(0)
    
    return pdf_buffer


def export_campaign_to_pdf(campaign: dict, trend: str, category: str, image_url: str = None) -> bytes:
    """
    Convenience function to export campaign to PDF bytes.
    
    Returns:
        bytes: PDF file as bytes
    """
    pdf_buffer = create_campaign_pdf(campaign, trend, category, image_url)
    return pdf_buffer.read()
